
name: Ben Eustace

description: Seniour SRE

avatar: https://raw.githubusercontent.com/krubot/krubot.github.io/master/images/computer.gif

footer-links:
  email: benpeustace@gmail.com
  github: krubot
  linkedin: ben-eustace-35a062101

url: http://krubot.github.io

permalink: /:title/

version: v4.3.4

sass:
  style: :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
